DutchTreat/DutchTreat/Controllers/AppController.cs
using DutchTreat.Data.Contracts;
using DutchTreat.Helpers;
using DutchTreat.Models;
using DutchTreat.Services.MailService;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace DutchTreat.Controllers
{
    public class AppController : Controller
    {
        protected IMailService _mailService { get; }
        protected IDutchRepository _repository { get; }

        public AppController(IMailService mailService, IDutchRepository repository)
        {
            _mailService = mailService;
            _repository = repository;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Contact()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Contact(Contact contact)
        {
            if (ModelState.IsValid)
            {
                _mailService.SendMessage("maksim_golev@epam.com", contact.Subject, contact.Message);
                ViewBag.UserMessage = "Mail sent";
                ModelState.Clear();
            }
            else
            {

            }

            return View();
        }

        public IActionResult About()
        {
            ViewBag.Title = "About Us";

            return View();
        }

        public IActionResult Shop()
        {
            return View();
        }
    }
}

DutchTreat/DutchTreat/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>Dutch Treat: @ViewBag.Title</title>
    <environment names="Development">
        <link href="~/node_modules/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />
        <link href="~/node_modules/font-awesome/css/font-awesome.css" rel="stylesheet" />
        <link href="~/css/site.css" rel="stylesheet" />
    </environment>
    <environment names="Staging,Production">
        <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" />
        <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" />
        <link href="~/css/site.css" rel="stylesheet" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div><i class="fa fa-paint-brush"></i>Dutch Treat</div>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li><a asp-controller="App" asp-action="Index">Home</a></li>
                <li><a asp-controller="App" asp-action="Contact">Contact</a></li>
                <li><a asp-controller="App" asp-action="About">About</a></li>
                <li><a asp-controller="App" asp-action="Shop">Shop</a></li>
                @if (User.Identity.IsAuthenticated)
                {
                    <li><a asp-controller="Account" asp-action="Logout">Logout</a></li>
                }
                else
                {
                    <li><a asp-controller="Account" asp-action="Login">Login</a></li>
                }
            </ul>
        </div>
    </nav>

    <section>
        <h2 class="text-center">@ViewBag.Title</h2>
        @RenderBody()
    </section>

    <footer class="container">
        <div class="text-center">Copyright 2018 Dutch Treat LLC</div>
    </footer>

    <environment names="Development">
        <script src="~/node_modules/jquery/dist/jquery.js"></script>
        <script src="~/node_modules/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/index.js"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-test="window.jQuery"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"></script>
        <script src="~/dist/dutchTreat.min.js" asp-append-version="true"></script>
    </environment>
    @RenderSection("scripts", false)
</body>
</html>